-- Active: 1734301207878@@127.0.0.1@3306@library_db

SELECT * FROM books;

SELECT * FROM books ORDER BY price DESC;

-- FINDING MAX VALUE:
SELECT MAX(price) FROM books;

--FINDING SECOND MAX VALUE USING OFFSET:
SELECT * FROM books ORDER BY price DESC LIMIT 1,1;

-- FINDING SECOND MAX VALUE IN A DIFFERENT WAY:
SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books);

-- FINDING THIRD MAX VALUE USING LOGIC:
SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books));

-- FINDING FOURTH MAX VALUE USING LOGIC:
SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books WHERE price < (SELECT MAX(price) FROM books))); 

-- FINDING MAX VALUE WITH TOTAL ROWS OR DETAILS:
SELECT * FROM books WHERE price = (SELECT MAX(price) FROM books);

